# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aewDu7cNLF241RL-mFccvcFSh62Jb3df
"""

print ("Hello World!")